### ISSUE TITLE
Peb files aren't recognized as HTML in Intellij

### ISSUE THREAD

**Issue by hevb** [HappyValleyIO/springboard#17]
IntelliJ doesn't recognize my pebble files as being HTML and so can't format them properly.

How do I configure the project so that IntelliJ will recognize them as HTML and give proper auto-complete, formatting, etc?

**Comment by stepbeekio** [comment]
Bottom of the Developing section of the README lays this out:

https://github.com/HappyValleyIO/springboard#developing


> Another step toward great dev flow is to mark the base language of pebble files as HTML. You can do this by:
> 
>     Opening Settings Ctrl + Alt + S
>     Navigating to Languages & Frameworks
>     Opening Template Data Languages
>     Adding the src/main/resources/templates directory and marking the base language as HTML
>
